### ISSUE TITLE
Log/Error/Warn On State Dead End

### ISSUE THREAD

**Issue by Jropp** [jrobinson01/fn-machine#1]
Since a UI change without a corresponding state change can essentially lock you out of any more UI changes, it would be helpful to have a warning or error thrown that you are currently in a dead end state. It might also be helpful to include the _previous_ state change before getting to the dead end.

**Example **
If you set up appropriate states/transitions for opening and closing a dialog (using a close/cancel button) but you forgot to set up an appropriate state for a user clicking outside of the dialog. The UI works fine, there are no errors, but now any attempt to initiate further transitions won't work because you are stuck in the wrong state with no path out of it.

![Screen Shot 2019-10-23 at 12 23 10 PM](https://user-images.githubusercontent.com/23724997/67413822-e6a1c280-f58f-11e9-865c-cad25df4d22b.png)

**Comment by jrobinson01** [comment]
I've added an optional 'logger' function as the last parameter to `machine()` that should give you what you want.
